env = "aat"
subscription = "nonprod"
vault_env = "test"

auth_provider_service_client_baseurl = "http://betaDevBccidamS2SLB.reform.hmcts.net"
logging_level_org_springframework_web = "DEBUG"
logging_level_uk_gov_hmcts_ccd = "DEBUG"
draft_store_api_baseurl = "https://testdraftstorelb.moneyclaim.reform.hmcts.net:4302"
pdf_generator_base_url = "https://betaDevBdivorceAppLB.reform.hmcts.net:4017"
uk_gov_notify_email_templates = "{SAVE_DRAFT:'9fbb6bdb-1043-440a-b082-5ea71b5c2609'}"
ccd_casedatastore_baseurl = "https://case-data-app.test.ccd.reform.hmcts.net:4481"
