env = "aat"
subscription = "nonprod"
vault_env = "test"

auth_provider_service_client_baseurl = "http://betaDevBccidamS2SLB.reform.hmcts.net:80"
logging_level_org_springframework_web = "DEBUG"
logging_level_uk_gov_hmcts_ccd = "DEBUG"
draft_store_api_baseurl = "https://testdraftstorelb.moneyclaim.reform.hmcts.net:4302"
uk_gov_notify_email_templates = "{SAVE_DRAFT:'45e71039-f3ca-4865-aa27-a6cc3253ec27'}"
ccd_casedatastore_baseurl = "https://case-data-app.test.ccd.reform.hmcts.net:4481"
