env = "sandbox"
subscription = "sandbox"
vault_env = "test"

auth_provider_service_client_baseurl = "http://betaDevBccidamS2SLB.reform.hmcts.net:80"
logging_level_org_springframework_web = "DEBUG"
logging_level_uk_gov_hmcts_ccd = "DEBUG"
draft_store_api_baseurl = "https://testdraftstorelb.moneyclaim.reform.hmcts.net:4302"
uk_gov_notify_email_templates = "{SAVE_DRAFT:'14074c06-87f1-4678-9238-4d71e741eb57'}"
uk_gov_notify_email_template_vars = "{SAVE_DRAFT: {divorceUrl: 'https://div-frontend-sandbox.service.core-compute-sandbox.internal'}}"
